gsm/person/urls.py
from django.urls import path

from . import views

app_name = 'person'

urlpatterns = [
    path('novo/', views.person_create, name='person_create'),
    # path('nova/', views.PersonFormView, name='PersonFormView'),
    path('nova/', views.PersonFormView.as_view(), name='PersonFormView'),
    # path('nova/', views.CreatePerson.as_view(), name='CreatePerson'),
    path('<int:id>/editar/', views.person_update, name='person_update'),
    path('listar/', views.person_client_list, name='person_client_list'),
]

gsm/persons/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'persons'


urlpatterns = [
    path('funcionarios/', views.employees, name='employees'),
    # url(r'clientes/editar/(?P<person_id>\d+)/endereco/$', address, name='address'),
    path('clientes/endereco/novo/', views.address, name='address'),
    path('clientes/listar/', views.clients_list, name='clients_list'),
    path('clientes/', views.clients, name='clients'),
    path('clientes/editar/<int:pk>/', views.clients_edit, name='clients_edit'),

    # path('clientes/notas/lista/', views.InvoiceSingleTableView.as_view(), name='invoice_list'),
    path('clientes/notas/nova/', views.InvoiceFormView.as_view(), name='invoice_add'),
    path('clientes/notas/edita/<int:id>/', views.InvoiceUpdateView.as_view(), name='invoice_edit'),

    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

gsm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('gsm.core.urls')),
    path('', include('gsm.accounts.urls')),
    path('financeiro/', include('gsm.financial.urls')),
    path('pessoa/', include('gsm.person.urls')),
    path('pessoas/', include('gsm.persons.urls')),
    path('admin/', admin.site.urls),
]

gsm/persons/models.py
# from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Person(models.Model):
    name = models.CharField('Nome',max_length=100)
    birthday = models.DateField('Aniversário')
    observation = models.CharField('Observações',max_length=100)
    purchase_limit = models.DecimalField('Limite de compra',max_digits=15, decimal_places=2)


    class Meta:
        verbose_name_plural = 'pessoas 2'
        verbose_name = 'pessoa 2'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/cadastro/pessoas'


class Address(models.Model):
    KINDS = (
        ('P', 'PRINCIPAL'),
        ('C', 'COBRANÇA'),
        ('E', 'ENTREGA'),
    )
    person = models.ForeignKey('persons.Person', related_name='addresses', on_delete=models.CASCADE)
    kind = models.CharField('Tipo', max_length=1, choices=KINDS)
    public_place = models.CharField('Logradouro',max_length=150)
    number = models.CharField('Número',max_length=150)
    city = models.CharField('Cidade',max_length=150)
    state = models.CharField('Estado',max_length=150)
    zipcode = models.CharField('Cep',max_length=10)
    country = models.CharField('País',max_length=150)
    neighborhood = models.CharField('Bairro',max_length=50)

    class Meta:
        verbose_name_plural = 'endereços'
        verbose_name = 'endereço'
        unique_together = ('person', 'kind')

    def __str__(self):
        return self.public_place


class Client(Person):
    compra_sempre = models.BooleanField('Compra Sempre',default=False)

    def save(self, *args, **kwargs):
        super(Client, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('persons:clients_editar', args=[str(self.id)])

    class Meta:
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'


class Employee(Person):
    ctps = models.CharField('Carteira de Trabalho',max_length=25)
    salary = models.DecimalField('Salário',max_digits=15, decimal_places=2)

    def save(self, *args, **kwargs):
        # self.operacao = CONTA_OPERACAO_DEBITO
        super(Employee, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Funcionário'
        verbose_name_plural = 'Funcionários'
# --------------------------------------------------------------------------------------------------------------------


class Customer(models.Model):
    name = models.CharField('name', max_length=255)

    def __str__(self):
        return self.name


class Invoice(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    total = models.IntegerField('Total')

    created = models.DateTimeField('created', auto_now_add=True)
    modified = models.DateTimeField('modified', auto_now=True)

    def get_absolute_url(self):
        return reverse('invoicing:invoice_detail', args=(self.pk,))


KIND_DOCUMENT = (
    ('0', 'RG'),
    ('1', 'CPF'),
    ('2', 'CNH'),
    ('3', 'Comprovante Endereço'),
)


class Item(models.Model):
    invoice = models.ForeignKey(Invoice, on_delete=models.CASCADE)
    kind = models.TextField('Tipo Documento', max_length=1, choices=KIND_DOCUMENT)
    file_document = models.FileField(upload_to='documents/')
    title = models.CharField('title', max_length=255)
    quantity = models.DecimalField('quantity', max_digits=10, decimal_places=3, default=1)
    unit_price = models.DecimalField('unit price', max_digits=10, decimal_places=2)

    created = models.DateTimeField('created', auto_now_add=True)
    modified = models.DateTimeField('modified', auto_now=True)

gsm/person/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.db import transaction
from django.db.models import Q
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.urls import reverse_lazy
from django.views.generic import FormView
from material.base import LayoutMixin, Layout, Fieldset, Row, Span9, Span4, Span12, Span3, Span2, Span8, Span5

from gsm.core.materialLayout import Inline
from gsm.person.forms import PersonForm, FileDocumentFormSet, ContactForm
from gsm.person.models import Person, FilesDocuments, Contact


# def create_person(request):
#     template_name = 'person_create0.html'
#     person_form = Person()
#     person_document_formset = inlineformset_factory(
#         Person,
#         FilesDocuments,
#         form=FilesDocumentsForms,
#         extra=0,
#         min_num=1,
#         validate_min=True,
#     )
#     if request.method == 'POST':
#         form = PersonForm(request.POST, request.FILES, instance=person_form,prefix='main')
#         formset = person_document_formset(request.POST, request.FILES, instance=person_form, prefix='person')
#         if form.is_valid() and formset.is_valid():
#             form = form.save()
#             formset.save()
#             url = 'person:create_person'
#             return HttpResponseRedirect(resolve_url(url, form.pk))
#     else:
#         form = PersonForm(instance=person_form, prefix='main')
#         formset = person_document_formset(instance=person_form, prefix='person')
#     context = {'form': form, 'formset': formset}
#     return render(request, template_name, context)


# class FilesDocumentsInline(InlineFormSetFactory):
#     model = FilesDocuments
#     fields = '__all__'
#     # fields = ['id', 'kynd', 'file_document']
#     # extra = 1
#     factory_kwargs = {'extra': 2, 'max_num': None,
#                       'can_order': False, 'can_delete': False}
#     formset_kwargs = {'auto_id': 'my_id_%s'}
#
#
# class ContactInline(InlineFormSetFactory):
#     model = Contact
#     fields = '__all__'
#     # fields = ['description', 'contact']
#     # extra = 1
#     factory_kwargs = {'extra': 1, 'max_num': None,
#                       'can_order': False, 'can_delete': False}
#     formset_kwargs = {'auto_id': 'my_id_%s'}
#
#
# class CreatePerson(CreateWithInlinesView, LayoutMixin):
#     model = Person
#     inlines = [ContactInline, FilesDocumentsInline]
#
#     fields = ['name', 'phone', 'cpf_cnpj', 'email', 'nascimento', 'rg', 'cep', 'logradouro', 'numero', 'bairro',
#               'cidade', 'estado']
#
#     layout = Layout(
#         Fieldset('Pessoa',
#                  Row(Span9('name'), Span3('nascimento'), ),
#                  Row(Span4('phone'), Span4('cpf_cnpj'), Span4('rg')),
#                  Row(Span12('email'), ),
#                  ),
#         Fieldset('Endereço',
#                  Row(Span2('cep'), Span8('logradouro'), Span2('numero')),
#                  Row(Span5('bairro'), Span5('cidade'), Span2('estado')),
#                  # Inline('Qualificações da Profissão', ContactInline),
#                  # Inline('Qualificações da Profissão', FilesDocumentsInline),
#                  ),
#
#     )
#
#     template_name = 'person_create_contact.html'


class PersonFormView(SuccessMessageMixin, FormView):
    form_class = PersonForm
    template_name = 'person_create_contact.html'
    success_url = reverse_lazy('person:person_client_list')
    success_message = 'The person was created correctly.'

    def get_context_data(self, **kwargs):
        context = super(PersonFormView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['contact_formset'] = ContactForm(self.request.POST, prefix='contacts')
            context['file_formset'] = FileDocumentFormSet(self.request.POST, self.request.FILES, prefix='files')
        else:
            context['contact_formset'] = ContactForm(prefix='contacts')
            context['file_formset'] = FileDocumentFormSet(prefix='files')
        print('-----------------CONTEXT------------------')
        print(context)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        contact_formset = context['contact_formset']
        file_formset = context['file_formset']
        total = 0
        if contact_formset.is_valid() and file_formset.is_valid():
            person = form.save(commit=False)
            person.save()

            contact_formset.instance = person
            contact_formset.save()

            file_formset.instance = person
            file_formset.save()
            # for item_form in contact_formset.forms:
            #     item = item_form.save(commit=False)
            #     item.person = person
            #     item.save()
            #     total += item.quantity * item.unit_price
            # person.total = total
            # person.save()
            return super(PersonFormView, self).form_valid(form)
        else:
            print('-----------------FORM INVALIDO------------------')
            print(file_formset)
            return self.render_to_response(self.get_context_data(form=form))
        
        
def person_create(request, ):
    if request.method == 'POST':
        form = PersonForm(request.POST)

        contact_formset = ContactFormSet(request.POST)

        file_document_formset = FileDocumentFormSet(request.POST, request.FILES)

        if form.is_valid() and contact_formset.is_valid() and file_document_formset.is_valid():
            with transaction.atomic():

                person_form = form.save()

                contact_formset.instance = person_form
                contact_formset.save()

                file_document_formset.instance = person_form
                file_document_formset.save()

                return redirect('/pessoa/listar/')
        else:
            return render(request, 'person_create_contact.html',
                          {'form': form,
                           'contact_formset': contact_formset,
                           'file_document_formset': file_document_formset})
    else:
        form = PersonForm()
        contact_formset = ContactFormSet()
        file_document_formset = FileDocumentFormSet()

    forms = [file_document_formset.empty_form] + file_document_formset.forms + \
            [contact_formset.empty_form] + contact_formset.forms
    print(str(file_document_formset))
    context = {'form': form,
               'contact_formset': contact_formset,
               'file_document_formset': file_document_formset,
               'forms': forms}
    # from django.template.loader import render_to_string
    # context2 = render_to_string('person_create_contact.html', {'file_document_formset': file_document_formset})
    # print(context2)
    return render(request, 'person_create_contact.html', context)


def person_update(request, id):
    # Pega a chave da URL acima com (request, pk)
    # joga na variável person na linha abaixo passando o modelo MESTRE e os parâmetros que desejo como filtro
    person = get_object_or_404(Person, id=id)

    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        contact_formset = ContactFormSet(request.POST, request.FILES, instance=person)
        file_document_formset = FileDocumentFormSet(request.POST, request.FILES, instance=person)

        if form.is_valid() and contact_formset.is_valid() and file_document_formset.is_valid():
            with transaction.atomic():

                person_form = form.save()

                contact_formset.instance = person_form
                contact_formset.save()

                file_document_formset.instance = person_form
                file_document_formset.save()

                return redirect('/pessoa/listar/')
            # return redirect('/pergunta/' + str(question.pk) + '/editar')
        else:
            print('<<<<==== AVISO DE FORMULARIO INVALIDO ====>>>>')

            print('/n-------------------------', file_document_formset)
            return render(request, 'person_create_contact.html',
                          {'form': form,
                           'contact_formset': contact_formset,
                           'file_document_formset': file_document_formset})
    else:
        form = PersonForm(instance=person)
        contact_formset = ContactFormSet(instance=person)
        file_document_formset = FileDocumentFormSet(instance=person)
        print(str(file_document_formset))
        # curl 'person_create_contact.html'

    forms = [file_document_formset.empty_form] + file_document_formset.forms + \
            [contact_formset.empty_form] + contact_formset.forms
    context = {'form': form,
               'contact_formset': contact_formset,
               'file_document_formset': file_document_formset,
               'forms': forms}
    return render(request, 'person_create_contact.html', context)


@login_required
def person_client_list(request):
    q = request.GET.get('searchInput')
    # print(request.GET)
    if q:
        persons = Person.objects.filter(Q(name__icontains=q))

    else:
        # persons = Person.objects.none()
        persons = Person.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(persons, 13)

    try:
        persons = paginator.page(page)
    except PageNotAnInteger:
        persons = paginator.page(1)
    except EmptyPage:
        persons = paginator.page(paginator.num_pages)

    context = {'persons': persons}
    return render(request, 'person_client_list.html', context)

gsm/persons/templates/form.html
<!--INCLUINDO O FORM FICA LEGAL E SEM FUNCIONAR, RETIRANDO FICA FEIO EM FUNCIONANDO-->
{% extends "account/base.html" %}
<!--{% load static %}-->



<!--{% include 'material/includes/material_css.html' %}
<script src="{% static 'material/js/jquery.js' %}"></script>
{% include 'material/includes/material_js.html' %}-->


{% load material_form %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Agendamento" %}{% endblock %}

{% block inner %}


    <form method="POST">
        {% csrf_token %}
        <!--{% form form=form %}{% endform %}-->
        {% form %}

        {% endform %}
        <button type="submit" name="_submit" class="btn">Submit</button>
    </form>


{% endblock %}

gsm/persons/templates/invoice_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
  <div class="col-md-12">
    <p>
      <a href="{% url 'invoicing:invoice_list' %}" class="btn btn-primary">Invoice list</a>
    </p>
  </div>
  <br>
  <div class="col-lg-12">
    <h2>Edit Invoice</h2>
    <br>
    {% bootstrap_form_errors form %}

    {% bootstrap_formset_errors formset %}

    <form method="post" role="form" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
    {% bootstrap_form_errors form %}
    {% bootstrap_formset_errors formset %}
      <fieldset>
        {% bootstrap_form form %}
      </fieldset>
      <fieldset>
        <table class="table">
          <thead>
          <th>Title</th>
          <th>Quantity</th>
          <th>Unit price</th>
          <th></th>
          </thead>
          {{ formset.management_form }}
          <tbody>
          {% for item_form in formset.forms %}
            {% for hidden in item_form.hidden_fields %}
              {{ hidden }}
            {% endfor %}
            <tr class="formset">
              <td class="col-md-8">{% bootstrap_field item_form.title show_label=False %}</td>
              <td class="col-md-2">{% bootstrap_field item_form.quantity show_label=False %}</td>
              <td class="col-md-2">{% bootstrap_field item_form.unit_price show_label=False %}</td>
              <td class=""></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </fieldset>
      <br><br>
      {% buttons %}
        <button type="submit" class="btn btn-primary pull-right">Edit invoice</button>
      {% endbuttons %}
    </form>
  </div>
{% endblock %}

{% block js %}
  <script src="{% static 'js/jquery.formset.min.js' %}"></script>
  <script src="{% static 'js/invoice_form.js' %}"></script>
{% endblock %}

gsm/persons/templates/invoice_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% load render_table from django_tables2 %}

{% block content %}
  <div class="col-md-12">
    <p>
      <a href="{% url 'invoicing:invoice_add' %}" class="btn btn-primary">New invoice</a>
    </p>
  </div>
  <br>
  <div class="col-md-12">
    {% render_table table %}
  </div>
{% endblock %}

gsm/persons/templates/person.html
{% extends "index.html" %}
{% load static %}
{% load material_form %}
{% load i18n %}
{% block container %}
<div class="card larger" id="card-radius">
    <form method="POST" id="person_form">
        {% csrf_token %}

            <div class="card-content">
                {% form form=form %}

                {% endform %}
            </div>

        <a class="tiny btn-floating waves-effect waves-light modal-trigger teal greem" href="#modal1"><i class="tiny material-icons">add</i></a>
        <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal 1</a>



        <br><br>

        <table id="address_table" class="bordered highlight">
            <thead class="#cfd8dc blue-grey lighten-4">
                <tr>
                    <th>Tipo</th>
                    <th>Logradouro</th>
                    <th>Número</th>
                    <th>Cidade</th>
                    <th>Estado</th>
                    <th>Cep</th>
                    <th>País</th>
                    <th>Bairro</th>
                    <th></th>
                    <th></th>

                </tr>
            </thead>

            <tbody>

                <!--<tr>-->
                    <!--<td>Principal</td>-->
                    <!--<td>Rua 1</td>-->
                    <!--<td>1234</td>-->
                    <!--<td>Maracanaú</td>-->
                    <!--<td>Ceará</td>-->
                    <!--<td>60.160-210</td>-->
                    <!--<td>Brasil</td>-->
                    <!--<td>Centro</td>-->
                    <!--<td><a class="tiny btn-floating waves-effect waves-light teal lighten-2"><i class="tiny material-icons">mode_edit</i></a></td>-->
                    <!--<td><a class="tiny btn-floating waves-effect waves-light red"><i class="tiny material-icons">delete</i></a></td>-->
                <!--</tr>-->

            </tbody>
        </table>

        <br>
        <button type="submit" name="_submit" class="btn">Salvar</button>
    </form>

</div>

{% endblock %}

{% block js %}
<script src="{% static 'js/add_address.js' %}"></script>

<!--<script type="text/javascript">-->

<!--    cep_value = document.getElementById("id_zipcode");-->

<!--    logradouro = document.getElementById("id_public_place");-->
<!--    bairro = document.getElementById("id_neighborhood");-->
<!--    localidade = document.getElementById("id_city");-->
<!--    uf = document.getElementById("id_state");-->
<!--    country = document.getElementById("id_country");-->

<!--    logradouro.readOnly = true;-->
<!--    bairro.readOnly = true;-->
<!--    localidade.readOnly = true;-->
<!--    uf.readOnly = true;-->
<!--    country.readOnly = true;-->

<!--    cep_value.addEventListener("keyup",function(event){-->

<!--        if (this.value.length == 8){-->

<!--            headers = new Headers();-->
<!--            headers.append("Access-Control-Allow-Origin","*")-->

<!--            data = fetch("https://viacep.com.br/ws/"+ this.value +"/json/",headers)-->
<!--                .then(function(response){-->

<!--                    Promise.resolve(response.json()).then(function(value){-->

<!--                        logradouro.value = value.logradouro;-->
<!--                        bairro.value = value.bairro;-->
<!--                        localidade.value = value.localidade;-->
<!--                        uf.value = value.uf;-->
<!--                        country.value = 'Brasil';-->

<!--                        // Adiciona a classe 'active' aos campos já preenchidos, isto faz com que o-->
<!--                        // 'label' do campo fique 'alto'-->
<!--                        document.getElementById("id_neighborhood_container").className='active';-->
<!--                        document.getElementById("id_public_place_container").childNodes[3].className='active';-->
<!--                        document.getElementById("id_city_container").childNodes[3].className='active';-->
<!--                        document.getElementById("id_state_container").childNodes[3].className='active';-->
<!--                    });-->

<!--                }).catch(function(error){-->
<!--                    console.log(error);-->
<!--                });-->
<!--        }-->
<!--    });-->
<!--    $('#btn_save').click(addNewAddress);-->
<!--</script>-->
{% endblock%}

gsm/persons/templates/person_address.html
{% extends "account/base.html" %}

{% load material_form %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Address" %}{% endblock %}

{% block inner %}

    <form method="POST">
        {% csrf_token %}
        <!--{% form form=form %}{% endform %}-->
        {% form form=form %}

        {% endform %}
        <button type="submit" name="_submit" class="btn">Submit</button>
    </form>


{% endblock %}

gsm/persons/templates/person_addresses.html
{% extends "account/base.html" %}

{% load material_form %}

{% load i18n %}
{% load crispy_forms_tags %}

{% block head_title %}{% trans "Agendamento" %}{% endblock %}

{% block inner %}

    <form method="POST">
        {% csrf_token %}
        <!--{% form form=form %}{% endform %}-->
        {% form form=form layout=view.layout %}
            {% part form.name prefix %}<i class="material-icons prefix">person</i>{% endpart %}
            {% part form.birthday prefix %}<i class="material-icons prefix">perm_contact_calendar</i>{% endpart %}
        {% endform %}
        <button type="submit" name="_submit" class="btn">Salvar <i class="material-icons right">send</i></button>
        <a class="waves-effect waves-light btn modal-trigger" href="#modal-persons-addesses">Endereços Modal + </a>
        <a class="waves-effect waves-light btn modal-trigger" href="/cadastro/clientes/endereco/novo/">Endereços Template + </a>
    </form>


      <!-- Modal Structure -->
      <div id="modal-persons-addesses" class="modal modal-fixed-footer">
        <div class="modal-content">
          <h4>Endereço</h4>
           {{ addressform }}
        </div>
        <div class="modal-footer">
          <button type="submit" name="_submit" class="btn">Salvar <i class="material-icons right">send</i></button>
          <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Agree</a>
        </div>
      </div>

{% endblock %}

gsm/persons/templates/person_and_professions.html
{% extends "account/base.html" %}

{% load material_form %}

{% load i18n %}


{% block inner %}

    <form method="POST">
        {% csrf_token %}
        <!--{% form form=form %}{% endform %}-->
        {% form form=form layout=view.layout %}{% endform %}
        <button type="submit" name="_submit" class="btn">Submit</button>
    </form>


{% endblock %}

gsm/persons/templates/persons.html
{% extends "index.html" %}
{% load static %}
{% load material_form %}
{% load i18n %}
{% block container %}

<div class="card larger" id="card-radius">

    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="card-content">
                {% form form=form %}

                {% endform %}

                <a class="tiny btn-floating waves-effect waves-light modal-trigger teal greem" href="#modal-persons-addesses"><i class="tiny material-icons">add</i></a>
            </div>

        <div class="card-content">
            <table id="address_table" class="bordered highlight">
                <thead class="#cfd8dc blue-grey lighten-4">
                    <tr>
                        <th>Tipo</th>
                        <th>Logradouro</th>
                        <th>Número</th>
                        <th>Cidade</th>
                        <th>Estado</th>
                        <th>Cep</th>
                        <th>País</th>
                        <th>Bairro</th>
                        <th></th>
                        <th></th>

                    </tr>
                </thead>

                <tbody>

                    <!--<tr>-->
                        <!--<td>Principal</td>-->
                        <!--<td>Rua 1</td>-->
                        <!--<td>1234</td>-->
                        <!--<td>Maracanaú</td>-->
                        <!--<td>Ceará</td>-->
                        <!--<td>60.160-210</td>-->
                        <!--<td>Brasil</td>-->
                        <!--<td>Centro</td>-->
                        <!--<td><a class="tiny btn-floating waves-effect waves-light teal lighten-2"><i class="tiny material-icons">mode_edit</i></a></td>-->
                        <!--<td><a class="tiny btn-floating waves-effect waves-light red"><i class="tiny material-icons">delete</i></a></td>-->
                    <!--</tr>-->

                </tbody>
            </table>

        </div>

  <!-- Modal Structure -->
<div id="modal-persons-addesses" class="modal modal-fixed-footer">
    <div class="modal-content">
        <h5>Endereço</h5>

        <div class="row">
            <form class="col s12">
                <div class="row">
                    <div class="input-field col s3">
                        <select id="id_tipo">
                            <option value="" disabled selected>Escolha aqui</option>
                            <option value="1">Principal</option>
                            <option value="2">Cobrança</option>
                            <option value="3">Entrega</option>
                        </select>
                        <label>Tipo</label>
                    </div>

                    <div class="input-field col s3">
                        <input id="id_zipcode" type="text" class="validate">
                        <label for="id_zipcode">Cep</label>
                    </div>

                    <div class="input-field col s6">
                        <input id="id_neighborhood" type="tel" class="validate">
                        <label for="id_neighborhood">Bairro</label>
                    </div>
                </div>

                <div class="row">
                    <div class="input-field col s9">
                        <input id="id_public_place" type="tel" class="validate">
                        <label for="id_public_place">Logradouro</label>
                    </div>
                    <div class="input-field col s3">
                        <input id="id_number" type="text" class="validate">
                        <label for="id_number">Número</label>
                    </div>
                </div>


                <div class="row">
                    <div class="input-field col s9">
                        <input id="id_city" type="tel" class="validate">
                        <label for="id_city">Cidade</label>
                    </div>
                    <div class="input-field col s3">
                        <input id="id_state" type="tel" class="validate">
                        <label for="id_state">Estado</label>
                    </div>

                </div>
            </form>
        </div>
    </div>

    <div class="modal-footer">
      <button type="button" id="btn_save" name="_submit" class="btn">Salvar <i class="material-icons right">send</i></button>
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
    </div>
</div>

        <br><br>

            <div class="card-action">
                <div class="right-align">
                    <button name="btn_submit" class="waves-effect waves-light btn" type="submit">Salvar</button>
                </div>
            </div>
    </form>


</div>

{% endblock %}