gsm/person/urls.py
from django.urls import path

from . import views

app_name = 'person'

urlpatterns = [
    path('novo/', views.person_create, name='person_create'),
    # path('nova/', views.PersonFormView, name='PersonFormView'),
    path('nova/', views.PersonFormView.as_view(), name='PersonFormView'),
    # path('nova/', views.CreatePerson.as_view(), name='CreatePerson'),
    path('<int:id>/editar/', views.person_update, name='person_update'),
    path('listar/', views.person_client_list, name='person_client_list'),
]

gsm/persons/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.views.i18n import JavaScriptCatalog

from . import views

app_name = 'persons'


urlpatterns = [
    path('funcionarios/', views.employees, name='employees'),
    # url(r'clientes/editar/(?P<person_id>\d+)/endereco/$', address, name='address'),
    path('clientes/endereco/novo/', views.address, name='address'),
    path('clientes/listar/', views.clients_list, name='clients_list'),
    path('clientes/', views.clients, name='clients'),
    path('clientes/editar/<int:pk>/', views.clients_edit, name='clients_edit'),

    # path('clientes/notas/lista/', views.InvoiceSingleTableView.as_view(), name='invoice_list'),
    path('clientes/notas/nova/', views.InvoiceFormView.as_view(), name='invoice_add'),
    path('clientes/notas/edita/<int:id>/', views.InvoiceUpdateView.as_view(), name='invoice_edit'),

    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

gsm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('gsm.core.urls')),
    path('', include('gsm.accounts.urls')),
    path('financeiro/', include('gsm.financial.urls')),
    path('pessoa/', include('gsm.person.urls')),
    path('pessoas/', include('gsm.persons.urls')),
    path('admin/', admin.site.urls),
]

gsm/person/forms.py
from django import forms
from django.forms import inlineformset_factory, formset_factory
from material import Layout, Fieldset, Span3, Row, Span12, Span9, Span4, Span2, Span8, Span5

from gsm.person.models import Person, Contact, FilesDocuments

KIND_CONTACT = (
    ('0', 'Telefone Fixo'),
    ('1', 'Celular 1'),
    ('2', 'Celular 2'),
    ('3', 'Celular 3'),
    ('4', 'E-Mail'),
    ('5', 'Telefone Trabalho'),
)


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = (
            'name',
            'phone',
            'cpf_cnpj',
            'email',
            'nascimento',
            'rg',
            'cep',
            'logradouro',
            'numero',
            'bairro',
            'cidade',
            'estado',
        )
        exclude = ('priority',)

    layout = Layout(
        Fieldset('Pessoa',
                 Row(Span9('name'), Span3('nascimento'), ),
                 Row(Span4('phone'), Span4('cpf_cnpj'), Span4('rg')),
                 Row(Span12('email'), ),
                 ),
        Fieldset('Endereço',
                 Row(Span2('cep'), Span8('logradouro'), Span2('numero')),
                 Row(Span5('bairro'), Span5('cidade'), Span2('estado'))
                 )
        )


class FileForm(forms.ModelForm):

    class Meta:
        model = FilesDocuments
        # fields = ('kind', 'file_document')
        exclude = ['id']


# widgets={'description': forms.TextInput(attrs={'class': 'input-field'}), },
ContactForm = inlineformset_factory(Person, Contact,
                                    exclude=('id',),
                                    can_delete=True,
                                    fields=('kind', 'description', 'contact'),
                                    extra=0,
                                    min_num=1)

# widgets={'description': forms.FileInput(attrs={'class': 'input-field'}), },
FileDocumentFormSet = inlineformset_factory(Person, FilesDocuments,
                                             exclude=('id',),
                                             can_delete=True,
                                             fields=('kind', 'file_document'),
                                             extra=0,
                                             min_num=1)

FileDocumentFormSet0 = formset_factory(FileForm,
                                      min_num=1,
                                      validate_min=True,
                                      extra=0,
                                      max_num=16,
                                      validate_max=True)

gsm/person/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import PageNotAnInteger, EmptyPage, Paginator
from django.db import transaction
from django.db.models import Q
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404, resolve_url
from django.urls import reverse_lazy
from django.views.generic import FormView
from material.base import LayoutMixin, Layout, Fieldset, Row, Span9, Span4, Span12, Span3, Span2, Span8, Span5

from gsm.core.materialLayout import Inline
from gsm.person.forms import PersonForm, FileDocumentFormSet, ContactForm
from gsm.person.models import Person, FilesDocuments, Contact


# def create_person(request):
#     template_name = 'person_create0.html'
#     person_form = Person()
#     person_document_formset = inlineformset_factory(
#         Person,
#         FilesDocuments,
#         form=FilesDocumentsForms,
#         extra=0,
#         min_num=1,
#         validate_min=True,
#     )
#     if request.method == 'POST':
#         form = PersonForm(request.POST, request.FILES, instance=person_form,prefix='main')
#         formset = person_document_formset(request.POST, request.FILES, instance=person_form, prefix='person')
#         if form.is_valid() and formset.is_valid():
#             form = form.save()
#             formset.save()
#             url = 'person:create_person'
#             return HttpResponseRedirect(resolve_url(url, form.pk))
#     else:
#         form = PersonForm(instance=person_form, prefix='main')
#         formset = person_document_formset(instance=person_form, prefix='person')
#     context = {'form': form, 'formset': formset}
#     return render(request, template_name, context)


# class FilesDocumentsInline(InlineFormSetFactory):
#     model = FilesDocuments
#     fields = '__all__'
#     # fields = ['id', 'kynd', 'file_document']
#     # extra = 1
#     factory_kwargs = {'extra': 2, 'max_num': None,
#                       'can_order': False, 'can_delete': False}
#     formset_kwargs = {'auto_id': 'my_id_%s'}
#
#
# class ContactInline(InlineFormSetFactory):
#     model = Contact
#     fields = '__all__'
#     # fields = ['description', 'contact']
#     # extra = 1
#     factory_kwargs = {'extra': 1, 'max_num': None,
#                       'can_order': False, 'can_delete': False}
#     formset_kwargs = {'auto_id': 'my_id_%s'}
#
#
# class CreatePerson(CreateWithInlinesView, LayoutMixin):
#     model = Person
#     inlines = [ContactInline, FilesDocumentsInline]
#
#     fields = ['name', 'phone', 'cpf_cnpj', 'email', 'nascimento', 'rg', 'cep', 'logradouro', 'numero', 'bairro',
#               'cidade', 'estado']
#
#     layout = Layout(
#         Fieldset('Pessoa',
#                  Row(Span9('name'), Span3('nascimento'), ),
#                  Row(Span4('phone'), Span4('cpf_cnpj'), Span4('rg')),
#                  Row(Span12('email'), ),
#                  ),
#         Fieldset('Endereço',
#                  Row(Span2('cep'), Span8('logradouro'), Span2('numero')),
#                  Row(Span5('bairro'), Span5('cidade'), Span2('estado')),
#                  # Inline('Qualificações da Profissão', ContactInline),
#                  # Inline('Qualificações da Profissão', FilesDocumentsInline),
#                  ),
#
#     )
#
#     template_name = 'person_create_contact.html'


class PersonFormView(SuccessMessageMixin, FormView):
    form_class = PersonForm
    template_name = 'person_create_contact.html'
    success_url = reverse_lazy('person:person_client_list')
    success_message = 'The person was created correctly.'

    def get_context_data(self, **kwargs):
        context = super(PersonFormView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['contact_formset'] = ContactForm(self.request.POST, prefix='contacts')
            context['file_formset'] = FileDocumentFormSet(self.request.POST, self.request.FILES, prefix='files')
        else:
            context['contact_formset'] = ContactForm(prefix='contacts')
            context['file_formset'] = FileDocumentFormSet(prefix='files')
        print('-----------------CONTEXT------------------')
        print(context)
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        contact_formset = context['contact_formset']
        file_formset = context['file_formset']
        total = 0
        if contact_formset.is_valid() and file_formset.is_valid():
            person = form.save(commit=False)
            person.save()

            contact_formset.instance = person
            contact_formset.save()

            file_formset.instance = person
            file_formset.save()
            # for item_form in contact_formset.forms:
            #     item = item_form.save(commit=False)
            #     item.person = person
            #     item.save()
            #     total += item.quantity * item.unit_price
            # person.total = total
            # person.save()
            return super(PersonFormView, self).form_valid(form)
        else:
            print('-----------------FORM INVALIDO------------------')
            print(file_formset)
            return self.render_to_response(self.get_context_data(form=form))
        
        
def person_create(request, ):
    if request.method == 'POST':
        form = PersonForm(request.POST)

        contact_formset = ContactFormSet(request.POST)

        file_document_formset = FileDocumentFormSet(request.POST, request.FILES)

        if form.is_valid() and contact_formset.is_valid() and file_document_formset.is_valid():
            with transaction.atomic():

                person_form = form.save()

                contact_formset.instance = person_form
                contact_formset.save()

                file_document_formset.instance = person_form
                file_document_formset.save()

                return redirect('/pessoa/listar/')
        else:
            return render(request, 'person_create_contact.html',
                          {'form': form,
                           'contact_formset': contact_formset,
                           'file_document_formset': file_document_formset})
    else:
        form = PersonForm()
        contact_formset = ContactFormSet()
        file_document_formset = FileDocumentFormSet()

    forms = [file_document_formset.empty_form] + file_document_formset.forms + \
            [contact_formset.empty_form] + contact_formset.forms
    print(str(file_document_formset))
    context = {'form': form,
               'contact_formset': contact_formset,
               'file_document_formset': file_document_formset,
               'forms': forms}
    # from django.template.loader import render_to_string
    # context2 = render_to_string('person_create_contact.html', {'file_document_formset': file_document_formset})
    # print(context2)
    return render(request, 'person_create_contact.html', context)


def person_update(request, id):
    # Pega a chave da URL acima com (request, pk)
    # joga na variável person na linha abaixo passando o modelo MESTRE e os parâmetros que desejo como filtro
    person = get_object_or_404(Person, id=id)

    if request.method == 'POST':
        form = PersonForm(request.POST, instance=person)
        contact_formset = ContactFormSet(request.POST, request.FILES, instance=person)
        file_document_formset = FileDocumentFormSet(request.POST, request.FILES, instance=person)

        if form.is_valid() and contact_formset.is_valid() and file_document_formset.is_valid():
            with transaction.atomic():

                person_form = form.save()

                contact_formset.instance = person_form
                contact_formset.save()

                file_document_formset.instance = person_form
                file_document_formset.save()

                return redirect('/pessoa/listar/')
            # return redirect('/pergunta/' + str(question.pk) + '/editar')
        else:
            print('<<<<==== AVISO DE FORMULARIO INVALIDO ====>>>>')

            print('/n-------------------------', file_document_formset)
            return render(request, 'person_create_contact.html',
                          {'form': form,
                           'contact_formset': contact_formset,
                           'file_document_formset': file_document_formset})
    else:
        form = PersonForm(instance=person)
        contact_formset = ContactFormSet(instance=person)
        file_document_formset = FileDocumentFormSet(instance=person)
        print(str(file_document_formset))
        # curl 'person_create_contact.html'

    forms = [file_document_formset.empty_form] + file_document_formset.forms + \
            [contact_formset.empty_form] + contact_formset.forms
    context = {'form': form,
               'contact_formset': contact_formset,
               'file_document_formset': file_document_formset,
               'forms': forms}
    return render(request, 'person_create_contact.html', context)


@login_required
def person_client_list(request):
    q = request.GET.get('searchInput')
    # print(request.GET)
    if q:
        persons = Person.objects.filter(Q(name__icontains=q))

    else:
        # persons = Person.objects.none()
        persons = Person.objects.all()

    page = request.GET.get('page', 1)
    paginator = Paginator(persons, 13)

    try:
        persons = paginator.page(page)
    except PageNotAnInteger:
        persons = paginator.page(1)
    except EmptyPage:
        persons = paginator.page(paginator.num_pages)

    context = {'persons': persons}
    return render(request, 'person_client_list.html', context)

gsm/person/templates/person_client_list.html
{% extends "index.html" %}
{% load static %}
{% load material_form %}



{% block container %}

    <div class="card larger" id="card-radius">
        <br>
        <div class="row">
            <form class="col s12">
                <div class="row">
                    <div class="input-field col s6 s12">
                        <i class="material-icons prefix">search</i>
                        <input id="searchInput" name="searchInput" type="text" class="validate" autofocus>
                        <label for="searchInput">Digite sua pesquisa aqui e tecle ENTER.</label>
                    </div>
                </div>
            </form>
        </div>
        <table class="highlight">
            <thead class="#cfd8dc blue-grey lighten-4">
                <tr>
                    <th class="center-align">CRM</th>
                    <th class="center-align">Id.</th>

                    <th>Nome</th>

                </tr>
            </thead>
            {% for person in persons %}
                <tr>
                    <td class="center-align">
                        <a href="/"><i class="material-icons prefix">home</i></a>
                    </td>
                    <td class="center-align">
                        <a href="{% url 'person:person_update' id=person.id %}">{{ person.id|linebreaks }}</a>
                    </td>
                    <td>
                        {{ person.name|linebreaks }}

                    </td>
                </tr>
            {% empty %}
                <div class="card-panel #424242 grey darken-3 center" id="empty-panel">NENHUM REGISTRO ENCONTRADO!</div>
            {% endfor %}
        </table>

        {% if persons.has_other_pages %}
          <ul class="pagination">


            {% if persons.has_previous %}
              <li><a href="#!"><i class="material-icons">chevron_left</i></a></li>
            {% else %}
              <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
            {% endif %}


            {% for i in persons.paginator.page_range %}
              {% if persons.number == i %}
                <li class="active"><a href="#!">{{ i }}</a></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}


            {% if persons.has_next %}

              <li><a href="?page={{ persons.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
            {% else %}
              <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
            {% endif %}
          </ul>
        {% endif %}

    </div>

{% endblock %}

gsm/person/templates/person_create.html
{% extends "index.html" %}
{% load static %}
{% load material_form %}
{% block container %}

    <div class="card larger" id="card-radius">
        <form method="POST" enctype="multipart/form-data">{% csrf_token %}

            <div class="card-content">
                {% form form=form %}
                    {% part form.name prefix %}<i class="material-icons prefix">person</i>{% endpart %}
                    {% part form.phone prefix %}<i class="material-icons prefix">phone</i>{% endpart %}
                    {% part form.email prefix %}<i class="material-icons prefix">contact_mail</i>{% endpart %}

                {% endform %}
            </div>

            <div class="card-action">
                <div class="right-align">
                    <button class="waves-effect waves-light btn" type="submit">Registrar</button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}

gsm/person/templates/person_create0.html
{% extends "index.html" %}
{% load static %}
{% load material_form %}
{% load i18n %}

{% block container %}

<a href="{% url 'person_client_list' %}">Voltar</a>

<div class="card" id="card-radius">

    <form method="POST" novalidate class="col s12">
      {% csrf_token %}
      <div class="row">
        <div class="col s12">
        <div class="card-content">
            {% form form=form %}
                {% part form.name prefix %}<i class="material-icons prefix">person</i>{% endpart %}
                {% part form.phone prefix %}<i class="material-icons prefix">phone</i>{% endpart %}
                {% part form.email prefix %}<i class="material-icons prefix">contact_mail</i>{% endpart %}
            {% endform %}
        </div>
        {{ formset.management_form }}
        </div>
      </div>

            {% for file_document_form in formset %}
                <div id="item2-{{ forloop.counter0 }}" class="form-group">

                    <tr>
                        <td>{{ file_document_form.kind.errors }} {{ file_document_form.kind }}</td>
                        <td>{{ file_document_form.file_document.errors }} {{ file_document_form.file_document }}</td>
                        <td>{{ file_document_form.id.errors }} {{ file_document_form.id }} {% if file_document_form.instance.pk %}{{ file_document_form.DELETE }}{% endif %}</td>
                        <td class="left-align">
                           <div class="switch">
                               <label>
                                   {{ file_document_form.DELETE.errors }}
                                   {{file_document_form.DELETE}}
                                <span class="lever"></span>
                               </label>
                           </div>
                        </td>
                    </tr>
                </div>
            {% endfor %}

      <div class="row">
        <div class="col s12">

          <div id="estoque" class="form-inline">
            {% for item_estoque_form in formset %}
              <div id="id_person-{{ forloop.counter0 }}" class="form-group">
                {{ item_estoque_form }}
              </div>
            {% endfor %}
          </div>
        </div>
      </div>

      <a class="btn-floating btn-small waves-light red" id="add-item"><i class="material-icons">add</i></a>

      <div class="row float-right">
        <div class="col-sm-12" style="margin-top: 10px;">
          <div class="form-inline buttons">
            <button class="btn btn-primary" value="Save">
              <i class="fa fa-floppy-o"></i>
              Salvar
            </button>
          </div>
        </div>
      </div>

    </form>
</div>

{% endblock container %}

{% block js %}

<script>
$('#add-item').click(function(ev) {
    ev.preventDefault();
    var count = $('#estoque').children().length;
    var tmplMarkup = $('#document-file').html();
    var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
    $('div#estoque').append(compiledTmpl);

    // update form count
    $('#id_person-TOTAL_FORMS').attr('value', count + 1);

    // some animate to scroll to view our new form
    $('html, body').animate({
      scrollTop: $("#add-item").position().top - 200
    }, 800);

    $('#id_estoque-' + (count) + '-produto').addClass('clProduto');
    $('#id_estoque-' + (count) + '-quantidade').addClass('clQuantidade');
    });
</script>

<script type="text/html" id="document-file">
  <div id="id_person-__prefix__" class="form-group">
    {{ formset.empty_form }}
  </div>
</script>
{% endblock js %}

gsm/person/templates/person_create_contact2.html
{% extends "index.html" %}
{% load static %}
{% load material_form %}
{% load i18n %}
{% block container %}
<div class="card" id="card-radius">
    <form class="form-container" id="myForm" method="POST" enctype="multipart/form-data">{% csrf_token %}
        <div class="card-content">
            {% form form=form %}
                {% part form.name prefix %}<i class="material-icons prefix">person</i>{% endpart %}
                {% part form.phone prefix %}<i class="material-icons prefix">phone</i>{% endpart %}
                {% part form.email prefix %}<i class="material-icons prefix">contact_mail</i>{% endpart %}
            {% endform %}
        </div>

        <div class="card-content">

            <h5>Anexe os documentos</h5>

            <table class="striped">
                <thead class="col s12">
                    <tr>
                        <th class="left-align">Documento</th>
                        <th class="left-align">Arquivo</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>

                {{ file_document_formset.management_form }}

                <tbody>
                    {% for file_document_form in file_document_formset %}
                        <tr>
                            <td>{{ file_document_form.kind.errors }} {{ file_document_form.kind }}</td>
                            <td>{{ file_document_form.file_document.errors }} {{ file_document_form.file_document }}</td>
                            <td class=""></td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>

            <h5>Adicione os Tipos de contatos</h5>
            <table class="striped">
                <thead class="col s12">
                    <tr>
                        <th class="left-align">Tipo Contato</th>
                        <th class="left-align">Descrição</th>
                        <th class="left-align">Pessoa Contato</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                {{ contact_formset.management_form }}
                <tbody>
                    {% for item_form in contact_formset.forms %}
                        <tr>
                            <td>{{ item_form.kind.errors }} {{ item_form.kind }}</td>
                            <td>{{ item_form.descriprion.errors }} {{ item_form.description }}</td>
                            <td>{{ item_form.contact.errors }} {{ item_form.contact }}</td>
                            <td class=""></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>


        </div>

        <div class="card-action">
            <div class="right-align">
                <button name="btn_submit" class="waves-effect waves-light btn" type="submit">Salvar</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

gsm/person/templates/person_create_contact_bkp.html
{% extends "index.html" %}
{% load static %}
{% load material_form %}
{% load i18n %}
{% block container %}

<div class="card larger" id="card-radius">

    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="card-content">
                {% form form=form %}
                    {% part form.name prefix %}<i class="material-icons prefix">person</i>{% endpart %}
                    {% part form.phone prefix %}<i class="material-icons prefix">phone</i>{% endpart %}
                    {% part form.email prefix %}<i class="material-icons prefix">contact_mail</i>{% endpart %}
                {% endform %}
            </div>

        <div class="card-content">
            <h5>Adicione os Tipos de contatos</h5>
            <table class="highlight">
                <thead class="#cfd8dc blue-grey lighten-4">
                    <tr>
                        <th class="left-align">Tipo Contato</th>
                        <th class="left-align">Descrição</th>
                        <th class="left-align">Pessoa Contato</th>
                        <th></th>
                        <th class="left-align">Deletar</th>

                    </tr>
                </thead>

                {{ contact_formset.management_form }}

                <tbody>
<!--                <button type="button" class="btn btn-flat grey lighten-4" style="padding:0px 40px;width:100%" data-formset-add=""><i class="material-icons">add</i></button>-->
                    {% for item_form in contact_formset %}
                          <tr>
                            <td>{{ item_form.kind.errors }} {{ item_form.kind }}</td>
                            <td>{{ item_form.descriprion.errors }} {{ item_form.description }}</td>
                            <td>{{ item_form.contact.errors }} {{ item_form.contact }}</td>
                            <td>{{ item_form.id.errors }} {{ item_form.id }}
                            <td class="left-align">
                               <div class="switch">
                                   <label>
                                       {{ item_form.DELETE.errors }}
                                       {{item_form.DELETE}}
                                    <span class="lever"></span>
                                   </label>
                               </div>
                            </td>
                          </tr>
                    {% endfor %}

                </tbody>
            </table>

            <h5>Adicione os documentos</h5>

            <table class="highlight">
                <thead class="#cfd8dc blue-grey lighten-4">
                    <tr>
                        <th class="left-align">Documento</th>
                        <th class="left-align">Arquivo</th>
                        <th></th>
                        <th class="left-align">Deletar</th>
                    </tr>
                </thead>

                {{ file_document_formset.management_form }}

                <tbody>
                    {% for file_document_form in file_document_formset %}
                          <tr>
                            <td>{{ file_document_form.kind.errors }} {{ file_document_form.kind }}</td>
                            <td>{{ file_document_form.file_document.errors }} {{ file_document_form.file_document }}</td>

                            <td>{{ file_document_form.id.errors }} {{ file_document_form.id }}</td>
                            <td class="left-align">
                               <div class="switch">
                                   <label>
                                       {{ file_document_form.DELETE.errors }}
                                       {{file_document_form.DELETE}}
                                    <span class="lever"></span>
                                   </label>
                               </div>
                            </td>
                          </tr>
                    {% endfor %}

                </tbody>
            </table>

        </div>

          <!-- Modal Trigger -->
  <a class="waves-effect waves-light btn modal-trigger" href="#modal1">Modal</a>

  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Modal Header</h4>
      <p>A bunch of text</p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
  </div>

        <br><br>

            <div class="card-action">
                <div class="right-align">
                    <button name="btn_submit" class="waves-effect waves-light btn" type="submit">Salvar</button>
                </div>
            </div>
    </form>


</div>

{% endblock %}

gsm/person/templates/receipt_form.html
{% extends "index.html" %}
{% load static %}
{% load widget_tweaks %}
{% load material_form %}
{% load i18n %}
{% block container %}

<div class="card larger" id="card-radius">

    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
            <div class="card-content">
                {% form %}

                {% endform %}
            </div>

        <div class="card-content">
            <table class="highlight">
                <thead class="#cfd8dc blue-grey lighten-4">
                <tr>
                    <th class="left-align">Pergunta</th>

                    <th class="right-align">Resposta</th>
                    <th></th>
                </tr>

                </thead>

                {{ formset.management_form }}

                <tbody>
                    {% for item_form in formset %}

                        <tr>

                            <td id="table-especial">{{ item_form.kind.errors }} {{ item_form.kind }}</td>

                            <td>{{ item_form.id.errors }} {{ item_form.id }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>


        <br><br>

            <div class="card-action">
                <div class="right-align">
                    <strong>Salvar e ir para:</strong>
                </div>
                <div class="right-align">
                    <button name="btn_submit_1" class="waves-effect waves-light btn" type="submit">Pesquisas de todos</button>
                    <button name="btn_submit_2" class="waves-effect waves-light btn" type="submit">Pesquisas Deste Cliente</button>
                </div>
            </div>
    </form>

</div>

{% endblock %}

        <script src="{% static 'js/jquery.formset.min.js' %}"></script>
        <script src="{% static 'js/invoice_form.js' %}"></script>